<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ElementarySchoolInspectionAdditionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '45. Are fire extinguishers located where they are visible from a distance? ',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are fire extinguishers located where they are visible from a distance? ',
                'name' => 'Are fire extinguishers located where they are visible from a distance? ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '46. Are fire extinguishers inspected monthly? *noted on extinguisher tag Are fire extinguishers inspected monthly? *noted on extinguisher tag ',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are fire extinguishers inspected monthly? *noted on extinguisher tag ',
                'name' => 'Are fire extinguishers inspected monthly? *noted on extinguisher tag ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),]
        ]);


        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '47. Are fire extinguishers in good condition and fully charged? *gauge will show green on visual inspection',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are fire extinguishers in good condition and fully charged? *gauge will show green on visual inspection',
                'name' => 'Are fire extinguishers in good condition and fully charged? *gauge will show green on visual inspection',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '48. Are electrical/mechanical rooms kept locked? * must be kept locked',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are electrical/mechanical rooms kept locked? *must be kept locked ',
                'name' => 'Are electrical/mechanical rooms kept locked? *must be kept locked ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '49. Are electrical/mechanical rooms free from storage?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are electrical/ mechanical rooms free from storage? ',
                'name' => 'Are electrical/ mechanical rooms free from storage? ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '50. Has the emergency lighting test been completed and signed off?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Has the emergency lighting test been completed and signed off?',
                'name' => 'Has the emergency lighting test been completed and signed off?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '51. Are wet floor signs available?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are wet floors signs available?',
                'name' => 'Are wet floors signs available?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => 'Personal Protective Equipment',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '52. Is personal protective equipment (PPE) available if required? Ie. rubber gloves, safety glasses',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is personal protective equipment (PPE) available if required? Ie. rubber gloves, safety glasses',
                'name' => 'Is personal protective equipment (PPE) available if required? Ie. rubber gloves, safety glasses',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '53. Is PPE being used when required? ',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is PPE being used when required? ',
                'name' => 'Is PPE being used when required? ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);


        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => 'Storage Facilities and Rooms',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '54. Are shelves/units at risk of falling, anchored firmly to the wall? *Storage of all items: heavy and breakable objects on low shelves, light objects on high shelves ',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are shelves/units at risk of falling, anchored firmly to the wall? *Storage of all items: heavy and breakable objects on low shelves, light objects on high shelves',
                'name' => 'Are shelves/units at risk of falling, anchored firmly to the wall? *Storage of all items: heavy and breakable objects on low shelves, light objects on high shelves',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '55. Is storage on top of wall-mounted cupboards limited to lightweight objects i.e. empty boxes? *storage must not be within 18” of ceiling ',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is storage on top of wall-mounted cupboards limited to lightweight objects i.e. empty boxes? *storage must not be within 18” of ceiling ',
                'name' => 'Is storage on top of wall-mounted cupboards limited to lightweight objects i.e. empty boxes? *storage must not be within 18” of ceiling ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '56. Are storage rooms organized so as not to present a safety hazard? *i.e. tripping hazard ',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are storage rooms organized so as not to present a safety hazard? *i.e. tripping hazard ',
                'name' => 'Are storage rooms organized so as not to present a safety hazard? *i.e. tripping hazard ',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => 'Other',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '57. Carts and dollies in good condition?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Carts and dollies in good condition?',
                'name' => 'Carts and dollies in good condition?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '58. TVs secured to carts safely?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'TVs secured to carts safely?',
                'name' => 'TVs secured to carts safely?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '59. Are appliances in good condition?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are appliances in good condition?',
                'name' => 'Are appliances in good condition?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '60. Is food stored in appropriate plastic containers and not left out to attract rodents?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is food stored in appropriate plastic containers and not left out to attract rodents?',
                'name' => 'Is food stored in appropriate plastic containers and not left out to attract rodents?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
            'forms_id' => 3,
            'title' => '61. Is garbage removed daily?',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is garbage removed daily?',
                'name' => 'Is garbage removed daily?',
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No, N/A',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Action',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'By Whom',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Date Completed',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),]
        ]);

    }
}
