<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class NonSchoolInspectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $form = DB::table('forms')->insertGetId([
            'title' => 'Non-School Inspection',
            'description' => '',
            'interval' => '1 year',
            'first_occurence_at' => '2020-09-30',
            'required_for' => '',
            'full_year' => false,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Date',
                'name' => Str::random(),
                'type' => 'date',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Time',
                'name' => Str::random(),
                'type' => 'time',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ]);


        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'JOHS Inspection Team',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Name 1',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Signature 1',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Name 2',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Signature 2',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '',
                'description' => 'RATE: A = High Risk   B = Medium Risk   C = Low Risk',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'A. WALKWAYS (INTERIOR)',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '1. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all walkways, aisles and doorways clear of obstacles?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '2. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all floor surfaces clean, i.e. no spills, grease, oil?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '3. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all holes, openings, etc. properly guarded?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '4. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are mats and gratins in good repair?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '5. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Does the layout of walkways allow easy evacuation in cases of emergency?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '6. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is there adequate room to move freely around desks, counters, equipment, and cabinets?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '7. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all extinguishers easily accessible?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '8. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Have all extinguishers been serviced annually?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '9. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is there alternative, emergency lighting available?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        DB::table('sections')->insert([
            'forms_id' => $form,
            'title' => 'B. STAIRS AND STAIRWAYS',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '1. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all stairs and stairways clear of all obstructions?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '2. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Do all stairs have treads in good order?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '3. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all handrails in place, in good order and according to regulations?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '4. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Do all stairways have adequate illumination',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '5. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all emergency exits clearly marked and free of obstructions?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'C. TO BE EDITED',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '6. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all cords in good order, no breaks, fraying, etc.?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '7. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are electrical cords secured to prevent tripping and other accidents?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '8. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'See filter change log on Ventilation Systems',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '9. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Fire blanket?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '10. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Emergency eye wash?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '11. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Emergency eye shower?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '12. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are ladders appropriate and in good repair?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'D. HYGIENE FACILITIES',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '1. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are washroom areas kept clean and in good order?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '2. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is the lunchroom clean and free of all contaminants, i.e. dust, fumes, noise, etc.?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'E. STORAGE AREAS',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '1. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are materials stored in a safe manner?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '2. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is the available storage space used efficiently?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '3. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are flammable materials and/or explosive materials stored in a safe manner?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'F. GENERAL HOUSEKEEPING ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '1. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Tripping hazard(s)',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '2. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Clearances',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '3. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Obstructions',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '4. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is floor surface clear of oil, grease, debris?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => 'G. TO BE EDITED',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '1. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are there plans and procedures for emergency situations: Bomb threats, Earthquake, Fire (Policy 5010.3, 3c)?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '2. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are all alarm systems working?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '3. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'What is the date of the last fire drill?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '5. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'First Aid Book location?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '6. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Name of First Aid attendant?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '7. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'First Aid certificate?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '8. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Is there reference to: A Notice of First Aid and Attendant?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '9. ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'Are accident records being maintained?',
                'name' => Str::random(),
                'type' => 'radio',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Rate',
                'name' => Str::random(),
                'type' => 'select',
                'required' => false,
                'options' => 'A,B,C',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
            ['sections_id' => $section,
                'label' => 'Explanation',
                'name' => Str::random(),
                'type' => 'text',
                'required' => false,
                'options' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],
        ]);

        $section = DB::table('sections')->insertGetId([
                'forms_id' => $form,
                'title' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('fields')->insert([
            ['sections_id' => $section,
                'label' => 'JOHS Committee comments (if required)',
                'name' => Str::random(),
                'type' => 'textarea',
                'required' => false,
                'options' => ' Yes, No',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),],

        ]);
    }
}
